### ISSUE TITLE
Netlify isn't handling subpaths

### ISSUE THREAD

**Issue by falquaddoomi** [colorado-cancer-center/ecco#51] opened 2024-03-22 16:51 UTC
Netlify throws a 404 if you access a subpage, e.g. "Sources": https://exploring-cancer-in-colorado.netlify.app/sources.

I assume this is because it hasn't been configured to send all requests to the root index where they can be handled by the router. 

FWIW, I'm fine to close this as wontfix since it doesn't affect "prod" (e.g., https://ecco.cu-dbmi.dev/sources works) and it doesn't impact navigating around the site from the index, just coming in from a link with a subpath, but I thought I'd bring it up if there's any easy fix.

**Comment by vincerubinetti** [comment] 2024-03-22 16:52
Duplicate of #47

**Closed by vincerubinetti** 2024-03-22 16:52 UTC
Labels: bug
